apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Apply the "watcher" namespace to all resources
namespace: watcher

# List of resources to include in the deployment
resources:
  - ../../base/postgres
  - ../../base/kratos
  - ../../base/hydra
  - ../../base/oathkeeper
  - ../../base/keto
  - ../../base/mailpit
  - ../../base/kratos-admin-ui
  - ../../base/api-gateway
  - ../../base/db-migrations
  - ../../base/api
  - namespace.yaml # The namespace itself must be created
  - postgres-secret.yaml
  - kratos-secret.yaml
  - hydra-secret.yaml
  - keto-secret.yaml

