apiVersion: v1
kind: Secret
metadata:
  name: hydra-secret
type: Opaque
stringData:
  DSN: postgres://watcher:watcher@postgres.watcher.svc.cluster.local:5432/watcher_hydra?sslmode=disable
  SECRETS_SYSTEM: "PLEASE_CHANGE_ME_I_AM_VERY_INSECURE"
  SECRETS_COOKIE: "PLEASE_CHANGE_ME_I_AM_VERY_INSECURE"
  URLS_LOGIN: "http://watcher.localhost/login"
  URLS_CONSENT: "http://watcher.localhost/consent"
  URLS_SELF_ISSUER: "http://watcher.localhost/api/v1/oauth2"
  SERVE_COOKIES_SAME_SITE_MODE: "Lax"
  DEV: "true"
  OAUTH2_TOKEN_HOOK_URL: "http://api-gateway:3000/api/v1/oauth2/token-hook"
  STRATEGIES_ACCESS_TOKEN: "jwt"
