apiVersion: v1
kind: Secret
metadata:
  name: keto-secret
type: Opaque
stringData:
  DSN: postgres://intheblack:WeAreInTheBlack@postgres.in-the-black.svc.cluster.local:5432/intheblack_keto?sslmode=disable
