apiVersion: v1
kind: Secret
metadata:
  name: kratos-secret
type: Opaque
stringData:
  DSN: postgres://intheblack:WeAreInTheBlack@postgres.in-the-black.svc.cluster.local:5432/intheblack_kratos?sslmode=disable
