apiVersion: v1
kind: Service
metadata:
  name: oathkeeper
spec:
  selector:
    app: oathkeeper
  ports:
    - name: http-proxy
      protocol: TCP
      port: 4455
      targetPort: 4455
    - name: http-api
      protocol: TCP
      port: 4456
      targetPort: 4456
