apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrations
spec:
  template:
    spec:
      containers:
        - name: db-migrations
          image: ghcr.io/petefromglasgow/in-the-black/db-migrations
          env:
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"
          envFrom:
            - secretRef:
                name: postgres-secret
      restartPolicy: Never
  backoffLimit: 4
