apiVersion: v1
kind: Service
metadata:
  name: hydra
spec:
  selector:
    app: hydra
  ports:
    - name: http-public
      protocol: TCP
      port: 4444
      targetPort: 4444
    - name: http-admin
      protocol: TCP
      port: 4445
      targetPort: 4445
