//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *KeywordFilters) DeepCopyInto(out *KeywordFilters) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of KeywordFilters.
func (in *KeywordFilters) DeepCopy() *KeywordFilters {
	if in == nil {
		return nil
	}
	out := new(KeywordFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *NotifierEntry) DeepCopyInto(out *NotifierEntry) {
	*out = *in
}

// DeepCopy creates a deep copy of NotifierEntry.
func (in *NotifierEntry) DeepCopy() *NotifierEntry {
	if in == nil {
		return nil
	}
	out := new(NotifierEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *TransportChainConfig) DeepCopyInto(out *TransportChainConfig) {
	*out = *in
	if in.Chain != nil {
		in, out := &in.Chain, &out.Chain
		*out = make([]TransportEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of TransportChainConfig.
func (in *TransportChainConfig) DeepCopy() *TransportChainConfig {
	if in == nil {
		return nil
	}
	out := new(TransportChainConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *TransportEntry) DeepCopyInto(out *TransportEntry) {
	*out = *in
}

// DeepCopy creates a deep copy of TransportEntry.
func (in *TransportEntry) DeepCopy() *TransportEntry {
	if in == nil {
		return nil
	}
	out := new(TransportEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *Watch) DeepCopyInto(out *Watch) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of Watch.
func (in *Watch) DeepCopy() *Watch {
	if in == nil {
		return nil
	}
	out := new(Watch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *Watch) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *WatchFilters) DeepCopyInto(out *WatchFilters) {
	*out = *in
	if in.PriceMin != nil {
		in, out := &in.PriceMin, &out.PriceMin
		*out = new(float64)
		**out = **in
	}
	if in.PriceMax != nil {
		in, out := &in.PriceMax, &out.PriceMax
		*out = new(float64)
		**out = **in
	}
	in.Keywords.DeepCopyInto(&out.Keywords)
}

// DeepCopy creates a deep copy of WatchFilters.
func (in *WatchFilters) DeepCopy() *WatchFilters {
	if in == nil {
		return nil
	}
	out := new(WatchFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *WatchList) DeepCopyInto(out *WatchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Watch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of WatchList.
func (in *WatchList) DeepCopy() *WatchList {
	if in == nil {
		return nil
	}
	out := new(WatchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements the runtime.Object interface.
func (in *WatchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *WatchSpec) DeepCopyInto(out *WatchSpec) {
	*out = *in
	in.Transport.DeepCopyInto(&out.Transport)
	if in.Notifiers != nil {
		in, out := &in.Notifiers, &out.Notifiers
		*out = make([]NotifierEntry, len(*in))
		copy(*out, *in)
	}
	in.Filters.DeepCopyInto(&out.Filters)
	if in.LLMQuestions != nil {
		in, out := &in.LLMQuestions, &out.LLMQuestions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of WatchSpec.
func (in *WatchSpec) DeepCopy() *WatchSpec {
	if in == nil {
		return nil
	}
	out := new(WatchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another object of the same type.
func (in *WatchStatus) DeepCopyInto(out *WatchStatus) {
	*out = *in
	if in.LastRunTime != nil {
		in, out := &in.LastRunTime, &out.LastRunTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of WatchStatus.
func (in *WatchStatus) DeepCopy() *WatchStatus {
	if in == nil {
		return nil
	}
	out := new(WatchStatus)
	in.DeepCopyInto(out)
	return out
}
