apiVersion: v1
kind: Service
metadata:
  name: keto
spec:
  selector:
    app: keto
  ports:
    - name: http-read
      protocol: TCP
      port: 4466
      targetPort: 4466
    - name: http-write
      protocol: TCP
      port: 4467
      targetPort: 4467
